server:
  port: 8080

spring:
  application:
    name: footballhub-auth-backend
  datasource:
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 300
      minimum-idle: 1
      idle-timeout: 300000
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 256
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
      schema: football
    url: jdbc:postgresql://localhost:5432/footballhub?currentSchema=admin&charSet=UTF8
    username: footballhub
    password: footballhub
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

jwt:
  secret-key: secret-key
  expire:
    access-token: 60
    refresh-token: 7
